# Site settings
title: My Blog
description: A blog about coding, technology, and software development.
url: "https://frobertpixto.github.io/blog" # the base hostname & protocol for your site

# Author settings
author:
  name: Francois Robert
  email: frobert@pixtolab.com

# Build settings
markdown: kramdown
remote_theme: jekyll/minima

# Permalinks
permalink: /:year/:month/:day/:title/

# Social media links
github_username: frobertpixto

